webtalk_init -webtalk_dir /home/bruno/Documents/PED/exp_3/exp_3.sim/sim_1/behav/xsim/xsim.dir/exp_3_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jan 22 15:09:09 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0a452b84-6047-40d4-9f9f-418857aa5cdb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7b1026c0f7d6436686581789fcec4a9b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "21" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Pop" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Pop!_OS 22.04 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1375.187 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "2.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "0 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "122748_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3130883625 -regid "" -xml /home/bruno/Documents/PED/exp_3/exp_3.sim/sim_1/behav/xsim/xsim.dir/exp_3_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/bruno/Documents/PED/exp_3/exp_3.sim/sim_1/behav/xsim/xsim.dir/exp_3_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/bruno/Documents/PED/exp_3/exp_3.sim/sim_1/behav/xsim/xsim.dir/exp_3_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
