webtalk_init -webtalk_dir /home/bruno/Documents/PED/test_1/test_1.sim/sim_1/behav/xsim/xsim.dir/adn2_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Dec 12 18:58:40 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0a452b84-6047-40d4-9f9f-418857aa5cdb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b2804b311f6d437bb2224fe2d2015062" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Pop" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Pop!_OS 22.04 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1501.638 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "2.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "115500_KB" -context "xsim\\usage"
webtalk_transmit -clientid 566242394 -regid "" -xml /home/bruno/Documents/PED/test_1/test_1.sim/sim_1/behav/xsim/xsim.dir/adn2_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/bruno/Documents/PED/test_1/test_1.sim/sim_1/behav/xsim/xsim.dir/adn2_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/bruno/Documents/PED/test_1/test_1.sim/sim_1/behav/xsim/xsim.dir/adn2_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
